### ISSUE TITLE
Try improving performance by temporarily disabling some extensions

### ISSUE THREAD

**Issue by lagleki** [lojban/lmw#1]
comment out these lines

```
require_once( "$IP/extensions/LogoFunctions/LogoFunctions.php" );//you can change the logo
require_once("$IP/extensions/CSS/CSS.php");
require_once "$IP/skins/Vector/Vector.php";
require_once "$IP/extensions/Mantle/Mantle.php";
require_once( 'extensions/Wikilog/Wikilog.php' );
require_once("$IP/extensions/WikiForum/WikiForum.php");
require_once("$IP/extensions/WebChat/WebChat.php");
require_once("$IP/extensions/DeleteBatch/DeleteBatch.php");
require_once( "$IP/extensions/Collection/Collection.php" );
```

**Comment by la-mukti** [comment]
Disabled all except Mantle (wiki apparently requires it) and Collection (already disabled). It may be worth investigating which components are actually resource intensive. I would expect extensions like the visual editor (especially since it depends on an additional process) and twitter integration (if it's synchronous) to slow things down.

**Comment by lagleki** [comment]
2015-07-06 14:55 GMT+03:00 Riley Martinez-Lynch notifications@github.com:

> Disabled all except Mantle (wiki apparently requires it)

I only knew Mantle was required for Flow and Extension:MobileFrontend but
the first is disabled and the second should no longer require it after MW
version 1.25.

Also note that WikiLog was requested by guskant and might be needed. I'm
just not sure if she uses it.

**Comment by lagleki** [comment]
2015-07-06 14:55 GMT+03:00 Riley Martinez-Lynch notifications@github.com:

> twitter integration

definitely possible to use external script to get updates to the wiki not
that fast.
the problem is that this script doesnt exist atm.

**Comment by lagleki** [comment]
2015-07-06 14:55 GMT+03:00 Riley Martinez-Lynch notifications@github.com:

> visual editor

well, if nothing helps we will have to disable it, yes. together with its
node.js colleague.
