### ISSUE TITLE
MathJax loads insecure content

### ISSUE THREAD

**Issue by lagleki** [lojban/lmw#10]
This is what needs to be solved for MathJax extension:

The page requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'.

The page requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/config/TeX-AMS-MML_HTMLorMML.js?rev=2.5.3'.

**Comment by durka** [comment]
Do we use MathJax or SimpleMathJax? The extension page for MathJax says it was retired and replaced by the SimpleMathJax. Assuming we use that there is a solution [here](https://www.mediawiki.org/wiki/Topic:Slfjbaas7sxv6b3b).

**Comment by lagleki** [comment]
la'oi SimpleMathJax i ki'e do

2015-08-31 17:06 GMT+03:00 Alex Burka notifications@github.com:

**Comment by lagleki** [comment]
fixed during update at ~2015-09-21T01:30 vrici timezone.
