### ISSUE TITLE
Metrolook has bugs like https://github.com/paladox/Metrolook/issues/109

### ISSUE THREAD

**Issue by lagleki** [lojban/lmw#6]
Metrolook has bugs like https://github.com/paladox/Metrolook/issues/109

**Comment by paladox** [comment]
Hi fixed problem I have submitted a patch here https://gerrit.wikimedia.org/r/#/c/227170/

**Comment by lagleki** [comment]
Hi, it's related to mw.lojban.org deployment. If it disappears after the next upgrade of mw.lojban.org then this issue will naturally disappear.

**Comment by paladox** [comment]
Ok  you would need to backport the fix once approved.

**Comment by lagleki** [comment]
fixed in the latest version of mw.lojban.org
